# Do not modify this file! [cite: 60]
# It was generated by ‘nixos-generate-config’ [cite: 60]
# and may be overwritten by future invocations. [cite: 60]
# Please make changes to /etc/nixos/configuration.nix instead. [cite: 61]
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # =========================================================================
  # Boot Configuration
  # =========================================================================
  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ]; # [cite: 62]
  boot.initrd.kernelModules = [ ]; # [cite: 62]
  boot.kernelModules = [ "kvm-amd" ]; # [cite: 62]
  boot.extraModulePackages = [ ]; # [cite: 63]

  # =========================================================================
  # File Systems
  # =========================================================================
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ecd21979-4027-46b2-a78d-ed330855f8dc";
    fsType = "ext4";
  }; # [cite: 63]

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F27E-5A7F";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  }; # [cite: 64]

  swapDevices = [ ]; # [cite: 65]

  # =========================================================================
  # Networking
  # =========================================================================
  # Enables DHCP on each ethernet and wireless interface.
  networking.useDHCP = lib.mkDefault true; # [cite: 68]
  # networking.interfaces.enp39s0.useDHCP = lib.mkDefault true;

  # =========================================================================
  # Platform & Hardware
  # =========================================================================
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux"; #
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware; #
}
