# Do not modify this file!
# It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
# Please make changes to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # =========================================================================
  # Boot Configuration
  # =========================================================================
  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ]; 
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # =========================================================================
  # File Systems
  # =========================================================================
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ecd21979-4027-46b2-a78d-ed330855f8dc";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/F27E-5A7F";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };

  swapDevices = [ ];

  # =========================================================================
  # Networking
  # =========================================================================
  # Enables DHCP on each ethernet and wireless interface.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp39s0.useDHCP = lib.mkDefault true;

  # =========================================================================
  # Platform & Hardware
  # =========================================================================
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux"; #
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware; #
}
